config/routes.rb
Cork::Application.routes.draw do

  root :to => 'pictures#instances'

  get  'tags'        => 'tags#instances'
  get  'tags/:id'    => 'tags#entry', as: 'tag'
  get  'tag/new'     => 'tags#new'
  post 'tags'        => 'tags#create', as: 'tag_create'

  get  'pictures'          => 'pictures#instances'
  get  'pictures/:id'      => 'pictures#entry', as: 'picture'
  get  'tags/:id/pictures' => 'pictures#grouped_by_tag', as: 'grouped_by_tag_pictures'
  get  'picture/new'       => 'pictures#new'
  get  'picture/add_tag'   => 'pictures#add_tag', as: 'picture_add_tag'
  post 'pictures'          => 'pictures#create', as: 'picture_create'

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  has_many :picture_tags
  has_many :tags, through: :picture_tags

  validates :url, uniqueness: true
  validates :url, format: { with: /\.(jpg|jpeg|png|gif)\z/i }

  attr :tag_name
end

app/models/picture_tag.rb
class PictureTag < ActiveRecord::Base
  belongs_to :picture
  belongs_to :tag

  validates :picture_id, uniqueness: { scope: [:tag_id] }
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :picture_tags
  has_many :pictures, through: :picture_tags

  attr :picture_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def instances
    @pictures = Picture.order("id DESC")
  end

  def entry
    @picture = Picture.find(params[:id])

    # add tag_names on picture object
    tag_ids = PictureTag.where([
      "picture_id = ?", @picture.id
    ]).pluck(:tag_id)
    @tags = Tag.find(tag_ids)

    # for new tag
    @tag = Tag.new

  end

  def grouped_by_tag
    @tag = Tag.find(params[:id])

    picture_ids = PictureTag.where([
      "tag_id = ?", @tag.id
    ]).pluck(:picture_id)

    @grouped_pictures = Picture.where(["id IN (?)", picture_ids]).order("id DESC")
  end

  def new
    @picture = Picture.new
  end

  def add_tag
    @picture = Picture.new({:url => picture_params[:url]})

    if @picture.valid?
    else
      render :add_tag, flash: { notice: @picture.errors.full_messages }
      return
    end
  end

  def create
    create_params = picture_params
    target_tag = Tag.find(:first, :conditions => ["name = ?", create_params[:tag_name]])

    unless defined? target_tag.id
      @tag = Tag.new({:name => picture_params[:tag_name]})
      @tag.save
      target_tag = @tag
    end

    @picture = Picture.new({
      :url       => picture_params[:url],
      :dangerous => picture_params[:dangerous]
    })

    if @picture.save
      target_tag.pictures << @picture
      redirect_to picture_path(@picture.id)
      return
    else
      target_picture = Picture.find(:first, :conditions => ["url = ?", @picture.url])
      if defined? target_picture.id
        redirect_to picture_path(target_picture.id), flash: { notice: 'same pic is already sticked!!' }
        return
      else
        redirect_to :back, flash: { error: @picture.errors.full_messages }
        return
      end
    end
  end

  private
    def picture_params
      params[:picture].permit(:url, :tag_name, :dangerous)
    end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:entry, :edit, :update, :destroy]

  def instances

    if defined? tag_params[:name]
      target_tag = Tag.find(:first, :conditions => ["name = ?", tag_params[:name]])

      unless defined? target_tag.id
        redirect_to pictures_path, flash: { notice: "requested tag is Not Found ><" }
        return
      end

      redirect_to grouped_by_tag_pictures_path(target_tag.id)
      return
    end

    @tags = Tag.all

    respond_to do |format|
      format.html { render action: 'instances' }
      format.json { render json: @tags.pluck(:name) }
    end
  end

  def entry
  end

  def new
    @tag = Tag.new
  end

  def create
    target_tag = Tag.find(:first, :conditions => ["name = ?", tag_params[:name]])
    @picture = Picture.find(:first, :conditions => ["id = ?", tag_params[:picture_id]])

    unless defined? target_tag.id
      @tag = Tag.new({:name => tag_params[:name]})
      @tag.save
      target_tag = @tag
      target_tag.pictures << @picture

      redirect_to picture_path(@picture.id)
      return
    else
      @picture_tag = PictureTag.new({
        :picture_id => @picture.id,
        :tag_id     => target_tag.id
      })

      if @picture_tag.save
        redirect_to picture_path(@picture.id)
        return
      else
        redirect_to picture_path(@picture.id), flash: { error: 'same tag is already sticked!!' }
        return
      end
    end

  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :picture_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cork</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header" style="width:100%">
      <%= link_to 'Cork', root_path, class: 'navbar-brand' %>

      <div style="width:300px; margin:0 auto;">
        <%= form_tag('/tags', :method => :get, id: 'tag_search', class: 'navbar-form navbar-left') do %>
          <div id="prefetch" class="form-group" align="center">
            <input id="tag_name" name="tag[name]" type="text" class="form-control typeahead" placeholder="Search">
          </div>
        <% end %>
      </div>

      <div class="navbar-btn navbar-right" style="text-align:right">
        <a href="<%= picture_new_path() %>" class="btn btn-default">+ Pic</a>
      </div>

    </div>
  </div>
  </header>
  <div class="container">
    <%= yield %>
  </div>
</body>
<script>
var tags = new Bloodhound({
  datumTokenizer: Bloodhound.tokenizers.whitespace,
  queryTokenizer: Bloodhound.tokenizers.whitespace,
  prefetch: '/tags.json'
});

// passing in `null` for the `options` arguments will result in the default
// options being used
$('#prefetch .typeahead').typeahead(null, {
  name: 'tags',
  source: tags
}).on("typeahead:selected typeahead:autocomplete", function(e, datum) {
  return $('#tag_search').submit();
});
</script>
</html>

app/views/pictures/add_tag.html.erb
<div class="page-header">
  <h1>+ Tag</h1>
</div>

<% if flash[:error] %>
  <div class="alert alert-danger">
    <%= flash[:error] %>
  </div>
<% end %>

<div style="text-align:center">
  <img src="<%= @picture.url %>">
</div>

<%= form_for @picture, :url => picture_create_path, :method => "post" do |f| %>

  <div class="form-group">
    <%= f.label :tag_name %><br>
    <%= f.text_field :tag_name %><br><br>
    <%= f.label :dangerous %>
    <%= f.check_box :dangerous, {}, 1, 0 %>
    <%= f.hidden_field :url, :value => @picture.url %>
  </div>

  <p>
    <%= f.submit 'Stick!!', class: 'btn btn-default', data: { disable_with: '...' } %>
  </p>

<% end %>

app/views/pictures/entry.html.erb
<h1>Picture No.<%= @picture.id %></h1>

<% if flash[:error] %>
  <div class="alert alert-danger">
    <%= flash[:error] %>
  </div>
<% end %>

  <div class="thumbnail">
    <a href="<%= @picture.url.match(/(http(?:s)?:\/\/[^\/]+)/)[1] %>" target="_blank"><img src="<%= @picture.url %>"></a>
    <div class="caption">
      <p align="center">
        <% @tags.each do |tag| %>
          <a href="<%= grouped_by_tag_pictures_path(tag.id) %>" class="btn btn-link btn-block">#<%= tag.name %></a>
        <% end %>
      </p>
    </div>
  </div>

<%= form_for @tag, :url => tag_create_path, :method => "post" do |f| %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
    <%= f.hidden_field :picture_id, :value => @picture.id %>
  </div>

  <p>
    <%= f.submit '+ Tag', class: 'btn btn-default', data: { disable_with: '...' } %>
  </p>

<% end %>

app/views/pictures/grouped_by_tag.html.erb
<h1>#<%= @tag.name %></h1>

<div class="container">
  <div class="row">
    <!--<div class="thumbnails">-->
    <div class="pins-grid">

      <% @grouped_pictures.each do |picture| %>
        <!--
        <div class="col-md-4">
          <div class="thumbnail">
            <img src="<%= picture.url %>">
          </div>
        </div>
        -->

        <div class="pin">
          <div class="image">
            <a href="../../pictures/<%= picture.id %>"><img data-src="<%= picture.url %>"/></a>
          </div>
        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/pictures/instances.html.erb
<div class="container">
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <div class="row">
    <div class="pins-grid">

      <% @pictures.each do |picture| %>

        <div class="pin">
          <div class="image">
            <a href="pictures/<%= picture.id %>"><img data-src="<%= picture.url %>"/></a>
          </div>
          <div class="credits">
            <p align="center"><a href="<%= grouped_by_tag_pictures_path(picture.tag_id) %>" class="btn btn-link btn-block">#<%= picture.tag.name %></a></p>
          </div>
        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/pictures/new.html.erb
<div class="page-header">
  <h1>+ Pic</h1>
</div>

<%= form_for @picture, :url => picture_add_tag_path, :method => "get" do |f| %>

<div class="form-group">
  <%= f.label :url %><br>
  <%= f.text_field :url %>
</div>

<p>
  <%= f.submit 'Confirm', class: 'btn btn-default', data: { disable_with: '...' } %>
</p>

<% end %>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/entry.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

app/views/tags/instances.html.erb
<h1>tags</h1>

  <% @tags.each do |tag| %>
      <p align="center"><a href="<%= grouped_by_tag_pictures_path(tag.id) %>" class="btn btn-link btn-block">#<%= tag.name %></a></p>
  <% end %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>